# Generated by Django 4.1.6 on 2023-10-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
