# Generated by Django 4.1.6 on 2023-10-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0002_alter_crime_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivercrime',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
