# Generated by Django 4.1.6 on 2023-10-07 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_carhistory_driver_alter_carhistory_owner'),
        ('accounts', '0002_address_workplace_staffprofile_driverprofile'),
        ('crimes', '0003_alter_drivercrime_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('crime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crimes.crime')),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staffprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='DriverCrime',
        ),
    ]
