# Generated by Django 4.1.6 on 2023-08-28 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_address_workplace_staffprofile_driverprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(blank=True, max_length=200, null=True)),
                ('steering', models.CharField(choices=[('راسته', 'راسته'), ('چپه', 'چپه')], default='راسته', max_length=10)),
                ('model', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=200)),
                ('engine_type', models.CharField(max_length=300)),
                ('engine_num', models.CharField(max_length=200)),
                ('number_of_cylinder', models.IntegerField()),
                ('chassis_num', models.CharField(help_text='شماره شاسی', max_length=200)),
                ('legal_weight', models.CharField(blank=True, help_text='وزن مجموعی مجاز', max_length=255, null=True)),
                ('weight_on_axle', models.CharField(blank=True, help_text='وزن بالای اکسل', max_length=255, null=True)),
                ('number_of_rider', models.CharField(help_text='تعداد راکبین', max_length=255)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.driverprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('آقا', 'آقا'), ('خانم', 'خانم')], default='آقا', max_length=10)),
                ('place_of_work', models.CharField(blank=True, max_length=200, null=True)),
                ('main_address', models.CharField(max_length=200)),
                ('current_address', models.CharField(max_length=200)),
                ('receivedـlocation', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Carowner/image')),
                ('id_image_front', models.ImageField(blank=True, null=True, upload_to='id/image')),
                ('id_image_back', models.ImageField(blank=True, null=True, upload_to='id/image')),
            ],
        ),
        migrations.CreateModel(
            name='JawazSayr',
            fields=[
                ('jawaz_num', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('card_num', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('statistic_num', models.CharField(blank=True, max_length=200, null=True)),
                ('document_num', models.CharField(blank=True, max_length=200, null=True)),
                ('document_date', models.DateTimeField(blank=True, null=True)),
                ('news_num', models.CharField(blank=True, max_length=200, null=True)),
                ('news_date', models.DateField(blank=True, null=True)),
                ('bank_reg_num', models.CharField(max_length=200)),
                ('bank_reg_date', models.DateField()),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('rest_assured', models.CharField(blank=True, help_text='اطمینانیه مستوفیت', max_length=255, null=True)),
                ('created', models.DateField()),
                ('expiry_date', models.DateField()),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.driverprofile')),
                ('verified_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffprofile')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carowner'),
        ),
    ]
