# Generated by Django 4.1.6 on 2023-08-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carowner',
            old_name='id_number',
            new_name='tazkira_number',
        ),
    ]
