# Generated by Django 4.1.6 on 2023-08-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_id_number_carowner_tazkira_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowner',
            name='receivedـlocation',
        ),
        migrations.AlterField(
            model_name='carowner',
            name='current_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='main_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
