# Generated by Django 4.1.6 on 2023-08-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_carowner_receivedـlocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
