# Generated by Django 4.1.6 on 2023-08-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_driver_alter_car_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number_of_rider',
            field=models.PositiveIntegerField(help_text='تعداد راکبین'),
        ),
    ]
