# Generated by Django 4.1.6 on 2023-09-05 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_workplace_staffprofile_driverprofile'),
        ('cars', '0007_carhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carhistory',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.driverprofile'),
        ),
        migrations.AlterField(
            model_name='carhistory',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.carowner'),
        ),
    ]
